<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Sales.aspx.cs" Inherits="CRUDoperations.Sales" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Sales Manage</title>
    <style>
        body {
            padding-left : 20px
        }
    </style>
</head>
<body>
    <div>
        <h1>Sales</h1>
    </div>
    
    <form id="sales" runat="server">
        <div>
            <asp:TextBox ID="TextBoxItemSize" runat="server" placeholder="Item Size"></asp:TextBox>
            <asp:TextBox ID="TextBoxItemType" runat="server" placeholder="Item Type"></asp:TextBox>
            <asp:TextBox ID="TextBoxItemPiece" runat="server" placeholder="Item Piece"></asp:TextBox>
            <asp:TextBox ID="TextBoxItemPrice" runat="server" placeholder="Item Price"></asp:TextBox>
            <asp:Button ID="ButtonSell" runat="server" Text="Sell" OnClick="ButtonSell_Click" />
            <asp:Button ID="ButtonBuy" runat="server" Text="Buy" OnClick="ButtonBuy_Click" />
        </div>
        <br />
        <br />
        <div>
            <asp:GridView ID="GridViewSales" runat="server" AutoGenerateDeleteButton="True" DataSourceID="ctl06" AutoGenerateEditButton="True" BorderStyle="Double" BorderWidth="1px"></asp:GridView>
            <asp:SqlDataSource runat="server" ConnectionString="<%$ ConnectionStrings:Salesconnect %>" DeleteCommand="DELETE FROM [Sales] WHERE [id] = @Id" InsertCommand="INSERT INTO [Sales] ([itemsize], [itemtype], [itempiece], [itemprice]) VALUES (@itemsize, @itemtype, @itempiece, @itemprice)" SelectCommand="SELECT * FROM [Sales]" UpdateCommand="UPDATE [Sales] SET [itemsize] = @itemsize, [itemtype] = @itemtype, [itempiece] = @itempiece, [itemprice] = @itemprice WHERE [Id] = @Id" ID="ctl06">
                <DeleteParameters>
                    <asp:Parameter Name="Id" Type="Int32"></asp:Parameter>
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="itemsize" Type="String"></asp:Parameter>
                    <asp:Parameter Name="itemtype" Type="String"></asp:Parameter>
                    <asp:Parameter Name="itempiece" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="itemprice" Type="Double"></asp:Parameter>
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="itemsize" Type="String"></asp:Parameter>
                    <asp:Parameter Name="itemtype" Type="String"></asp:Parameter>
                    <asp:Parameter Name="itempiece" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="itemprice" Type="Double"></asp:Parameter>
                    <asp:Parameter Name="Id" Type="Int32"></asp:Parameter>
                </UpdateParameters>
            </asp:SqlDataSource>
        </div>
        <br />
        <br />
        <div>
            <asp:Label ID="LabelNotification" runat="server" Text="Notification : "></asp:Label>
        </div>    
        <br />
        <br />
        <div>
            <asp:ListBox ID="ListBoxNotification" runat="server"></asp:ListBox>
        </div>
    </form>
    
</body>
</html>
